### ISSUE TITLE
Inconsistent application of standard names and units in topmodel

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/topmodel#20]
This takes a little winding around to see what is happening here, so start with [this definition](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/src/bmi_topmodel.c#L12) of a topmodel output variable.  It claims that output variable `p` is `atmosphere_water__domain_time_integral_of_rainfall_volume_flux` with units of `m h-1`.

Next, look at [this input variable](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/src/bmi_topmodel.c#L113) which maps to `rain` and claims to be `atmosphere_water__liquid_equivalent_precipitation_rate` with units of `kg m-2`.

We can then see that the [BMI Update function](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/src/bmi_topmodel.c#L389) passes both of these variables from its struct to the topmodel function.

But when you carefully [inspect topmodel](https://github.com/NOAA-OWP/topmodel/blob/479d00684971977bc39f44491515c49fc82ab37e/src/topmodel.c#L168), you can see that the code considers these two variables to be equivalent, assigning one to the other verbatim, with no transformation/conversion.

Even under an **_assumption_** that `kg/m^2 == mm/hr`, this doesn't match the units described by the variable `p`.

**Comment by peckhams** [comment]
The variable name should not include "domain", because we are integrating
over time but not over the model domain.
Integrating over the entire model domain is an area integral.  The rainfall
rate names should be either:
"atmosphere_water__time_integral_of_rainfall_volume_flux"   [canonical
units:  L3  L-2  T-1 = L  T-1] or
"atmosphere_water__time_integral_of_rainfall_mass_flux"   [canonical
units:   M  L-2  T-1]
where:  M = mass, L = length, T = time.

Use of the word "rainfall" in the name, instead of "precipitation" or
"snowfall", etc. indicates that the precipitation
rate is a "liquid equivalent" rate, vs. an actual rate.

Density of liquid water is around:  1000 kg m-3
Density of hail is around:               700 to 900 kg m-3
Density of graupel is around:         50 to 890 kg m-3
Density of fresh, dry snow is around:  20 to 200 kg m-3  (or 10 to 350,
another source)

**Comment by peckhams** [comment]
Sorry, I made an important mistake in my haste.
When the name includes "time_integral", the "per time" units go away, so:

atmosphere_water__rainfall_volume_flux.    [ L T-1]
atmosphere_water__time_integral_of_rainfall_volume_flux.   [ L ]
atmosphere_water__rainfall_mass_flux.    [ M  L-2  T-1]
atmosphere_water__time_integral_of_rainfall_mass_flux.   [ M. L-2 ]

**Comment by SnowHydrology** [comment]
@hellkite500 My reading of the code is that TOPMODEL expects input precipitation in m/h. That means that kg/m^2 is wrong for multiple reasons.
